function [ isInt ] = isInteger( x )
%ISINTEGER(x) if x is a scalar integer
%   Returns true if x is a scalar integer
isInt=~isempty(x) ...
    && isnumeric(x) ...
    && isreal(x) ...
    && all(isfinite(x)) ...
    && all(x == fix(x));
end

